name: Docker

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.22
      - name: Build Executables
        run: ./build.sh ${{ github.event.release.tag_name }}
      - name: Upload to Releases
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./build/dockonaut_*
          file_glob: true
